source 'https://artifactory.acorn.cirrostratus.org/artifactory/api/gems/gems' do

  gem 'activesupport',          '>= 3.2.6'
  gem 'aws-sdk-s3',             '~> 1.17.0'
  gem 'chunky_png',             '~> 1.3.5'
  gem 'forum_apis',             '~> 1.0.0'
  gem 'ithaka_utilities',       '~> 4.8'
  gem 'mailinator',             '~> 1.0.0'
  gem 'mechanize',              '~> 2.7.5'
  gem 'pact',                   '1.19.2'
  gem 'pact_broker-client',     '~> 1.16.1'
  gem 'pact-provider-proxy',    '~> 2.3.0'
  gem 'parallel_tests',         '~> 2.15.0'
  gem 'pg',                     '~> 1.0.0'
  gem 'rake',                   '~> 12.3.2'
  gem 'rest-client',            '~> 2.0.2'
  gem 'rspec',                  '~> 3.8'
  gem 'rubyXL',                 '~> 3.3.29'
  gem 'rubyzip',                '>= 1.0.0'
  gem 'spreadsheet',            '~> 1.1.4'

end